drop table if exists item cascade;
drop table if exists locker cascade;
drop table if exists member_product cascade;
drop table if exists orders cascade;
drop table if exists order_item cascade;
drop table if exists orderitem cascade;
drop table if exists product cascade;
drop table if exists team cascade;
drop table if exists member cascade;
drop table if exists category cascade;
drop table if exists category_item cascade;
drop table if exists item_category cascade;
drop table if exists delivery cascade;
drop table if exists movie cascade;
drop table if exists book cascade;
drop table if exists album cascade;
drop table if exists parent cascade;
drop table if exists child cascade;
drop table if exists address cascade;
drop table if exists favorite_food cascade;
drop table if exists parent_child cascade;
drop sequence if exists HIBERNATE_SEQUENCE;

commit;